name: CI
on: [push]
jobs:
  all-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests by using
      # https://github.com/cypress-io/github-action
      #
      # Need to run:
      #  - component tests (fast)
      #  - e2e tests (don't forget to start the application)
